      - name: Create ZIP of Project Files
        run: |
          zip -r birthday_card_v${{ github.ref_name }}.zip Happy_Birthday_index.html

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.intoto.jsonl
            Happy_Birthday_index.html
            birthday_card_v${{ github.ref_name }}.zip
            assets/screenshot.png  # Optional, if you add images
