      # ... previous steps ...
      - name: Upload Provenance to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.intoto.jsonl"
      - name: Upload Birthday Card HTML to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Happy_Birthday_index.html
